site_name: 奶茶伺服器 Wiki 頁面
site_url: https://wiki.milkteamc.org
site_description: 奶茶伺服器官方 Wiki：你的 Minecraft 冒險起點，從這裡開始探索、學習與創造。
site_author: Maoyue
repo_url: https://github.com/milkteamc/wiki
repo_name: milkteamc/wiki
edit_uri: edit/main/docs/

extra:
  homepage: https://wiki.milkteamc.org
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/22DxRjrXRv
    - icon: fontawesome/brands/github
      link: https://github.com/milkteamc

plugins:
  - privacy
  - social:
      cards_layout_options:
        font_family: Iansui
  - search:
      lang: zh
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - git-revision-date-localized:
      enable_creation_date: true
      locale: zh_TW
  - git-authors

theme:
  name: material
  favicon: image/logo.png
  logo: image/logo.png
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - content.action.edit
    - content.code.copy
  language: zh-TW
  font:
    text: Iansui
  palette:
    primary: black
    scheme: slate
    
  icon:
    edit: material/pencil 
    repo: fontawesome/brands/github

copyright: 來自「奶茶伺服器」 —— 程式碼以 GPL-3.0 條款開源，文字以【姓名標示─非商業性─相同方式分享 4.0 國際】條款共享

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
